### ISSUE TITLE
output paramerer for msslookup

### ISSUE THREAD

**Issue by husensofteng** [lehtiolab/msstitch#4]
It would be great to have an optional output parameter for the database created from msslookup
Currently, the databse is always written to mslookup_db.sqlite

**Comment by glormph** [comment]
Try commit 7c12d76964301ed31e11c0ab0cdde26c3ac7e237 

The commit after that may break stuff, as it changes an output, so be careful.

**Comment by glormph** [comment]
Think this issue has been fixed and released now, so closing.
